import { HorizontalBox } from "std-widgets.slint";
import { Letter } from "letter.slint";
import { WordModel } from "../models.slint";

export Word := HorizontalLayout {
    property <int> index: 0;
    property <WordModel> word;
    property <bool> selected: false;

    callback clicked();

    alignment: center;

    rect := Rectangle {
        TouchArea {
            clicked => {
                root.clicked()
            }
        }

        HorizontalLayout {
            spacing: 6px;

            Rectangle { 
                min-width: 46px;

                Text { 
                    width: parent.width;
                    height: parent.height;

                    horizontal-alignment: center;
                    vertical-alignment: center;

                    text: selected ? "➔" : root.index;
                    font-size: 16pt;
                }
            }
            
            for data in word.letters: Letter { 
                letter: data; 
            }
        }
    }
}