export struct LetterModel := {
    state: int,
    char: string,
}

export struct WordModel := {
    letters: [LetterModel]
}

export global WordSearcher := {
    property <[WordModel]> words;
    property <int> current-word-index: 0;
    property <string> search_words;

    callback key-pressed(string);
    callback letter-state-changed(int, int, int);
    callback clear-all();
    callback random();
}